# Generated by Django 5.1 on 2024-08-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class1File',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class2File',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class3File',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class4File',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class6File',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class7File',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 1 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 2 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 3 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 4 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 6 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 7 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class 8 File',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
