# Generated by Django 5.1 on 2024-08-29 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_teacher_class1file_remove_teacher_class2file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='ClassAssignment',
        ),
    ]
